package dev.codestijl.gradledocker;

/**
 * This class was generated by Gradle as part of the init process.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
