package dev.codestijl.gradledocker;

import org.junit.Test;
import static org.junit.Assert.*;

/**
 * This class was generated by Gradle as part of the init process.
 */
public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
